### ISSUE TITLE
suggestion: add react-redbox

### ISSUE THREAD

**Issue by puranjayjain** [delvallejonatan/generator-create-redux-app#2]
first of all thanks for the wonderful boilerplate. It saved me tremendous time and effort to get started with redux and reselect based scalable web app.

Just a suggestion we could have react-redbox as an addition to this project. It would mean incredibly useful runtime errors in the dom when in development mode.

**Comment by delvallejonatan** [comment]
Great sugestion but `redbox-react` It's intended to be used with with other existing solutions that automate the error catching for you like `react-hot-loader` ( the best one in my opinion )
Because `react-hot-loader` is in transition right now ( version 3 is coming out shortly ) implementing `redbox-react` now will be a waist of time. I will close this issue for now. Meanwhile `create-react-app` has new UI error handlers, and if that is not enough you can open this issue in the future when  `react-hot-loader` `v3` is out.

**Comment by puranjayjain** [comment]
Thanks @delvallejonatan
